# Generated by Django 5.0.2 on 2024-02-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('BookId', models.IntegerField(primary_key=True, serialize=False)),
                ('BookName', models.CharField(max_length=20)),
                ('BookAuthor', models.CharField(max_length=20)),
                ('BookPrice', models.IntegerField()),
                ('BookGenre', models.CharField(max_length=20)),
            ],
        ),
    ]
